[Feat] add at32 dma v1 low level driver
qmk-arterytek/ChibiOS-Contrib pull request #3
Opened 2023-08-27 13:38 UTC by zhaqian12

2023-09-01 13:05 UTC, HorrorTroll requested changes
Thanks for your pr, I've just take a look at reviewing your code. There are some code need to be changed first. And it seem there are 2 folder DMAv1 on LLD

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/AT32F41x/platform.mk
> +include $(CHIBIOS_CONTRIB)/os/hal/ports/AT32/LLD/DMAv1/driver.mk
I think DMA LLD should be above GPIO LLD
```suggestion
include $(CHIBIOS_CONTRIB)/os/hal/ports/AT32/LLD/DMAv1/driver.mk
include $(CHIBIOS_CONTRIB)/os/hal/ports/AT32/LLD/GPIOv1/driver.mk
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +#endif
Since DMA_CSELR is only available for STM32F0/L0, so those are unused for AT32F415.
```suggestion
#define DMA1_CH1_VARIANT            0
#define DMA1_CH2_VARIANT            0
#define DMA1_CH3_VARIANT            0
#define DMA1_CH4_VARIANT            0
#define DMA1_CH5_VARIANT            0
#define DMA1_CH6_VARIANT            0
#define DMA1_CH7_VARIANT            0
#define DMA2_CH1_VARIANT            0
#define DMA2_CH2_VARIANT            0
#define DMA2_CH3_VARIANT            0
#define DMA2_CH4_VARIANT            0
#define DMA2_CH5_VARIANT            0
#define DMA2_CH6_VARIANT            0
#define DMA2_CH7_VARIANT            0
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +
Since F415 don't have DMA1 Channel 8 so this goes unused.
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +
Same above
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +#endif
Same above
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +   * @brief   Mask of the enabled streams ISRs.
```suggestion
   * @brief   Mask of the enabled streams STSs.
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +  uint32_t          isr_mask;
```suggestion
  uint32_t          sts_mask;
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +    at32_dmaisr_t    func;
```suggestion
    at32_dmasts_t    func;
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * Default ISR collision masks.
```suggestion
 * Default STS collision masks.
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 1 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 2 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 3 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 4 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 5 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 6 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA1 stream 7 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +
Unused
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 1 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 2 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 3 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 4 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 5 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 6 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
```suggestion
 * @brief   DMA2 stream 7 shared STS.
 *
 * @sts
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +
Unused
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +    _at32_dma_streams[i].channel->CTRL = AT32_DMA_CCR_RESET_VALUE;
```suggestion
  dma.sts_mask       = 0U;
  for (i = 0; i < AT32_DMA_STREAMS; i++) {
    _at32_dma_streams[i].channel->CTRL = AT32_DMA_CTRL_RESET_VALUE;
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +                                          at32_dmaisr_t func,
```suggestion
                                          at32_dmasts_t func,
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +      dmastp->channel->CTRL = AT32_DMA_CCR_RESET_VALUE;
```suggestion
        if ((dma.sts_mask & dmastp->cmask) == 0U) {
          nvicEnableVector(dmastp->vector, priority);
        }
        dma.sts_mask |= mask;
      }

      /* Putting the stream in a known state.*/
      dmaStreamDisable(dmastp);
      dmastp->channel->CTRL = AT32_DMA_CTRL_RESET_VALUE;
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +                                         at32_dmaisr_t func,
```suggestion
                                         at32_dmasts_t func,
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +  if ((dma.isr_mask & dmastp->cmask) == 0U) {
```suggestion
  dma.sts_mask &= ~(1U << selfindex);

  /* Disables the associated IRQ vector if it is no more in use.*/
  if ((dma.sts_mask & dmastp->cmask) == 0U) {
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> +  flags = (dmastp->dma->STS >> dmastp->shift) & AT32_DMA_ISR_MASK;
```suggestion
  flags = (dmastp->dma->STS >> dmastp->shift) & AT32_DMA_STS_MASK;
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @note    This function can be invoked in both ISR or thread context.
```suggestion
 * @note    This function can be invoked in both STS or thread context.
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +#define AT32_DMA_ISR_MASK          0x0E
```suggestion
 * @brief   Mask of the STS bits passed to the DMA callback functions.
 */
#define AT32_DMA_STS_MASK          0x0E
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +#endif
Unused
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +#endif
Unused
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +#define AT32_DMA_CR_PL(n)          ((n) << 12U)
```suggestion
 * @name    CCTRL register constants common to all DMA types
 * @{
 */
#define AT32_DMA_CCTRL_RESET_VALUE  0x00000000U
#define AT32_DMA_CCTRL_CHEN         DMA_CCTRL_CHEN
#define AT32_DMA_CCTRL_DTERRIEN     DMA_CCTRL_DTERRIEN
#define AT32_DMA_CCTRL_HDTIEN       DMA_CCTRL_HDTIEN
#define AT32_DMA_CCTRL_FDTIEN       DMA_CCTRL_FDTIEN
#define AT32_DMA_CCTRL_DTD_MASK     (DMA_CCTRL_DTD | DMA_CCTRL_M2M)
#define AT32_DMA_CCTRL_DTD_P2M      0U
#define AT32_DMA_CCTRL_DTD_M2P      DMA_CCTRL_DTD
#define AT32_DMA_CCTRL_DTD_M2M      DMA_CCTRL_M2M
#define AT32_DMA_CCTRL_LM           DMA_CCTRL_LM
#define AT32_DMA_CCTRL_PINCM        DMA_CCTRL_PINCM
#define AT32_DMA_CCTRL_MINCM        DMA_CCTRL_MINCM
#define AT32_DMA_CCTRL_PWIDTH_MASK  DMA_CCTRL_PWIDTH
#define AT32_DMA_CCTRL_PWIDTH_BYTE  0U
#define AT32_DMA_CCTRL_PWIDTH_HWORD DMA_CCTRL_PWIDTH_0
#define AT32_DMA_CCTRL_PWIDTH_WORD  DMA_CCTRL_PWIDTH_1
#define AT32_DMA_CCTRL_MWIDTH_MASK  DMA_CCTRL_MWIDTH
#define AT32_DMA_CCTRL_MWIDTH_BYTE  0U
#define AT32_DMA_CCTRL_MWIDTH_HWORD DMA_CCTRL_MWIDTH_0
#define AT32_DMA_CCTRL_MWIDTH_WORD  DMA_CCTRL_MWIDTH_1
#define AT32_DMA_CCTRL_SIZE_MASK    (AT32_DMA_CCTRL_PWIDTH_MASK |           \
                                     AT32_DMA_CCTRL_MWIDTH_MASK)
#define AT32_DMA_CCTRL_CHPL_MASK    DMA_CCTRL_CHPL
#define AT32_DMA_CCTRL_CHPL(n)      ((n) << 12U)
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +
Unused
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +
CSELR not supported
```suggestion
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +typedef void (*at32_dmaisr_t)(void *p, uint32_t flags);
```suggestion
 * @param[in] flags     pre-shifted content of the STS register, the bits
 *                      are aligned to bit zero
 */
typedef void (*at32_dmasts_t)(void *p, uint32_t flags);
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +                                             and CSELR registers.           */
```suggestion
  uint8_t               dummy;          /**< @brief Filler.                 */
  uint8_t               shift;          /**< @brief Bit offset in STS, CLR  */
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +#endif
```suggestion
 * @param[in] mode      value to be written in the CCTRL register
 *
 * @special
 */
#define dmaStreamSetMode(dmastp, mode) {                                    \
  (dmastp)->channel->CCTRL = (uint32_t)(mode);                              \
}
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +  (dmastp)->channel->CTRL |= AT32_DMA_CR_EN;                                \
```suggestion
  (dmastp)->channel->CCTRL |= AT32_DMA_CCTRL_CHEN;                          \
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +                              AT32_DMA_CR_TEIE | AT32_DMA_CR_EN);         \
```suggestion
  (dmastp)->channel->CCTRL &= ~(AT32_DMA_CCTRL_FDTIEN |                     \
                                AT32_DMA_CCTRL_HDTIEN |                     \
                                AT32_DMA_CCTRL_DTERRIEN |                   \
                                AT32_DMA_CCTRL_CHEN);                       \
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +  (dmastp)->dma->CLR = AT32_DMA_ISR_MASK << (dmastp)->shift;              \
```suggestion
  (dmastp)->dma->CLR = AT32_DMA_STS_MASK << (dmastp)->shift;              \
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> + *                      - @p AT32_DMA_CR_EN
```suggestion
 * @param[in] mode      value to be written in the CCTRL register, this value
 *                      is implicitly ORed with:
 *                      - @p AT32_DMA_CCTRL_MINCM
 *                      - @p AT32_DMA_CCTRL_PINCM
 *                      - @p AT32_DMA_CCTRL_DTD_M2M
 *                      - @p AT32_DMA_CCTRL_CHEN
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +                           AT32_DMA_CR_DIR_M2M | AT32_DMA_CR_EN);         \
```suggestion
                           AT32_DMA_CCTRL_MINCM | AT32_DMA_CCTRL_PINCM |    \
                           AT32_DMA_CCTRL_DTD_M2M | AT32_DMA_CCTRL_CHEN);   \
```

2023-09-01 13:05 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.h
> +                                           at32_dmaisr_t func,
```suggestion
                                            at32_dmasts_t func,
                                            void *param);
  const at32_dma_stream_t *dmaStreamAlloc(uint32_t id,
                                           uint32_t priority,
                                           at32_dmasts_t func,
```

2023-09-02 02:11 UTC, zhaqian12 commented
Thanks for you review and suggestion and sorry for my carelessness. The changes have been committed, please check again, thank you!

2023-09-02 02:25 UTC, zhaqian12 commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
This is the DMA interrupt service routine,but STS is the reg name about dma isr flag.I think ISR is more appropriate, and consistent with at32_isr.c

2023-09-02 02:27 UTC, HorrorTroll commented
It fine, I'll re-take a look after I've got some free time 👍

2023-09-02 02:27 UTC, zhaqian12 commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
Or something like this 
~~~
/**
 * @brief   DMA1 stream 2 shared interrupt handler.
 *
 * @isr
 */
~~~

2023-09-02 02:29 UTC, zhaqian12 commented
Sorry, please wait a minute, some bugs are not fixed and commited yet

2023-09-08 08:06 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/DMAv1/at32_dma.c
> + * @isr
> Or something like this
> 
> ```
> /**
>  * @brief   DMA1 stream 2 shared interrupt handler.
>  *
>  * @isr
>  */
> ```

Yep, i think this is much more better.

2023-09-09 15:29 UTC, HorrorTroll reviewed
Last 2 need to fix and should be done. Make sure to testing out first both flexible and solid DMA on QMK and see if it work or not.

2023-09-09 15:29 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/at32_dma.c
> +#endif
I've forgot this on the last reviewer
```suggestion
```

2023-09-09 15:29 UTC, HorrorTroll commented on os/hal/ports/AT32/LLD/DMAv1/at32_dma.h
> +
Forgot about this, it needed for I2C and other peripherals.
```suggestion

/**
 * @name    Status flags passed to the ISR callbacks
 * @{
 */
#define AT32_DMA_STS_DTERRF    (0x1U << 3)
#define AT32_DMA_STS_HDTF        (0x1U << 2)
#define AT32_DMA_STS_FDTF         (0x1U << 1)
/** @} */

```

2023-09-09 15:46 UTC, zhaqian12 commented
Thanks a lot for your support!

2023-09-09 15:48 UTC, HorrorTroll approved these changes

2023-09-10 02:38 UTC, merged